export const STAFFS_LOADING = "STAFF_LOADING";
export const STAFFS_FAILED = "STAFF_FAILED";
export const ADD_STAFFS = "ADD_STAFFS";

export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";
export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS";

export const SALARYS_LOADING = "SALARYS_LOADING";
export const SALARYS_FAILED = "SALARYS_FAILED";
export const ADD_SALARYS = "ADD_SALARYS";
